### ISSUE TITLE
Todo-list

### ISSUE THREAD

**Issue by UnstoppableN** [UnstoppableN/Invasion-mod#1]
First:
- [x] Fix the todo list xD

Get @TehNut to fix the workspace (Will take a few days)
- [ ] Move everything into the new package structure.
- [ ] Clean up all the messy old code leftover from forever ago
- [ ] Organize _everything_

First update:
- [ ] Change config to the new, clean config like in SSTOW
- [x] Change the log to the new, clean log like in SSTOW
- [ ] Add nei support
- [ ] Hide the engineers hammer from the item list
- [ ] Add recipe handlers for the Nexus

Later updates:
- [ ] Add more traps
- [ ] Add more textures and assign them randomly
- [ ] Add friendly protectors (bound golem)
- [ ] Add some kind of sponge, make them function as one, craftable?
- [ ] Add lava/water engineer which remove lava/water with sponge?

Much later updates:
- [ ] Finish the flying monster
- [ ] Improve AI to make path more random

Varia:
- [ ] Lore
- [ ] Update to 1.8

**Comment by Beardedlizzy** [comment]
Firstly, hello, secondly, 1.8 was out last year?, third this looks like a lot for a to-do list, fourth, it doesn't seem like it is gonna be finished but hopefully in time to come it will be finished, fith, great mod and bye.

**Comment by Loweredgames** [comment]
is the mod still in development?
